<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make your donation now - Wikimedia Foundation</title>
    <link rel="stylesheet" href="<?= \App\Classes\Helper::url('/assets/style.css') ?>">
</head>
<body>
<div class="home-heading"></div>
<main class="main">
    <div class="container">
        <h4>We Understand</h4>
        <p>
            We thank you for your interest, we hope you will try some other time.
        </p>
        <a href="<?= \App\Classes\Helper::url() ?>" class="button">DONATE</a>
    </div>
</main>

</body>
</html>
