<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make your donation now - Wikimedia Foundation</title>
    <link rel="stylesheet" href="<?= \App\Classes\Helper::url('/assets/style.css') ?>">
</head>
<body>
<div class="home-heading"></div>
<main class="main">
    <div class="container">
        <h4>Thank you</h4>
        <p>We really appreciate your donation to free knowledge</p>
        <p>We will contact you shortly</p>
    </div>
</main>

</body>
</html>
