<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make your donation now - Wikimedia Foundation</title>
    <link rel="stylesheet" href="<?= \App\Classes\Helper::url('/assets/style.css') ?>">
</head>
<body>
<div class="home-heading"></div>
<main class="main">
    <div class="container">
        <h2>We ask you, humbly, to help.</h2>
        <form js-form>
            <label>
                <input type="text" class="form-control" placeholder="First name" name="first_name" required>
            </label>
            <label>
                <input type="text" class="form-control" placeholder="Last name" name="last_name" required>
            </label>
            <label>
                <input type="email" class="form-control" placeholder="Email" name="email" required>
            </label>
            <label>
                <input type="tel" class="form-control" placeholder="Phone number" name="phone" required>
            </label>
            <label>
                <input type="text" class="form-control" placeholder="Street Address" name="street_address" required>
            </label>
            <label>
                <input type="text" class="form-control" placeholder="City" name="city" required>
            </label>
            <label>
                <input type="text" class="form-control" placeholder="State" name="state" required>
            </label>
            <label>
                <select class="form-control" name="country" required id="country">
                    <option value="">Country</option>
                    <option value="Afghanistan">Afghanistan</option>
                    <option value="Albania">Albania</option>
                    <option value="Algeria">Algeria</option>
                    <option value="Andorra">Andorra</option>
                    <option value="Angola">Angola</option>
                    <option value="Antigua & Deps">Antigua & Deps</option>
                    <option value="Argentina">Argentina</option>
                    <option value="Armenia">Armenia</option>
                    <option value="Australia">Australia</option>
                    <option value="Austria">Austria</option>
                    <option value="Azerbaijan">Azerbaijan</option>
                    <option value="Bahamas">Bahamas</option>
                    <option value="Bahrain">Bahrain</option>
                    <option value="Bangladesh">Bangladesh</option>
                    <option value="Barbados">Barbados</option>
                    <option value="Belarus">Belarus</option>
                    <option value="Belgium">Belgium</option>
                    <option value="Belize">Belize</option>
                    <option value="Benin">Benin</option>
                    <option value="Bhutan">Bhutan</option>
                    <option value="Bolivia">Bolivia</option>
                    <option value="Bosnia Herzegovina">Bosnia Herzegovina</option>
                    <option value="Botswana">Botswana</option>
                    <option value="Brazil">Brazil</option>
                    <option value="Brunei">Brunei</option>
                    <option value="Bulgaria">Bulgaria</option>
                    <option value="Burkina">Burkina</option>
                    <option value="Burundi">Burundi</option>
                    <option value="Cambodia">Cambodia</option>
                    <option value="Cameroon">Cameroon</option>
                    <option value="Canada">Canada</option>
                    <option value="Cape Verde">Cape Verde</option>
                    <option value="Central African Rep">Central African Rep</option>
                    <option value="Chad">Chad</option>
                    <option value="Chile">Chile</option>
                    <option value="China">China</option>
                    <option value="Colombia">Colombia</option>
                    <option value="Comoros">Comoros</option>
                    <option value="Congo">Congo</option>
                    <option value="Congo {Democratic Rep}">Congo {Democratic Rep}</option>
                    <option value="Costa Rica">Costa Rica</option>
                    <option value="Croatia">Croatia</option>
                    <option value="Cuba">Cuba</option>
                    <option value="Cyprus">Cyprus</option>
                    <option value="Czech Republic">Czech Republic</option>
                    <option value="Denmark">Denmark</option>
                    <option value="Djibouti">Djibouti</option>
                    <option value="Dominica">Dominica</option>
                    <option value="Dominican Republic">Dominican Republic</option>
                    <option value="East Timor">East Timor</option>
                    <option value="Ecuador">Ecuador</option>
                    <option value="Egypt">Egypt</option>
                    <option value="El Salvador">El Salvador</option>
                    <option value="Equatorial Guinea">Equatorial Guinea</option>
                    <option value="Eritrea">Eritrea</option>
                    <option value="Estonia">Estonia</option>
                    <option value="Ethiopia">Ethiopia</option>
                    <option value="Fiji">Fiji</option>
                    <option value="Finland">Finland</option>
                    <option value="France">France</option>
                    <option value="Gabon">Gabon</option>
                    <option value="Gambia">Gambia</option>
                    <option value="Georgia">Georgia</option>
                    <option value="Germany">Germany</option>
                    <option value="Ghana">Ghana</option>
                    <option value="Greece">Greece</option>
                    <option value="Grenada">Grenada</option>
                    <option value="Guatemala">Guatemala</option>
                    <option value="Guinea">Guinea</option>
                    <option value="Guinea-Bissau">Guinea-Bissau</option>
                    <option value="Guyana">Guyana</option>
                    <option value="Haiti">Haiti</option>
                    <option value="Honduras">Honduras</option>
                    <option value="Hungary">Hungary</option>
                    <option value="Iceland">Iceland</option>
                    <option value="India">India</option>
                    <option value="Indonesia">Indonesia</option>
                    <option value="Iran">Iran</option>
                    <option value="Iraq">Iraq</option>
                    <option value="Ireland {Republic}">Ireland {Republic}</option>
                    <option value="Israel">Israel</option>
                    <option value="Italy">Italy</option>
                    <option value="Ivory Coast">Ivory Coast</option>
                    <option value="Jamaica">Jamaica</option>
                    <option value="Japan">Japan</option>
                    <option value="Jordan">Jordan</option>
                    <option value="Kazakhstan">Kazakhstan</option>
                    <option value="Kenya">Kenya</option>
                    <option value="Kiribati">Kiribati</option>
                    <option value="Korea North">Korea North</option>
                    <option value="Korea South">Korea South</option>
                    <option value="Kosovo">Kosovo</option>
                    <option value="Kuwait">Kuwait</option>
                    <option value="Kyrgyzstan">Kyrgyzstan</option>
                    <option value="Laos">Laos</option>
                    <option value="Latvia">Latvia</option>
                    <option value="Lebanon">Lebanon</option>
                    <option value="Lesotho">Lesotho</option>
                    <option value="Liberia">Liberia</option>
                    <option value="Libya">Libya</option>
                    <option value="Liechtenstein">Liechtenstein</option>
                    <option value="Lithuania">Lithuania</option>
                    <option value="Luxembourg">Luxembourg</option>
                    <option value="Macedonia">Macedonia</option>
                    <option value="Madagascar">Madagascar</option>
                    <option value="Malawi">Malawi</option>
                    <option value="Malaysia">Malaysia</option>
                    <option value="Maldives">Maldives</option>
                    <option value="Mali">Mali</option>
                    <option value="Malta">Malta</option>
                    <option value="Marshall Islands">Marshall Islands</option>
                    <option value="Mauritania">Mauritania</option>
                    <option value="Mauritius">Mauritius</option>
                    <option value="Mexico">Mexico</option>
                    <option value="Micronesia">Micronesia</option>
                    <option value="Moldova">Moldova</option>
                    <option value="Monaco">Monaco</option>
                    <option value="Mongolia">Mongolia</option>
                    <option value="Montenegro">Montenegro</option>
                    <option value="Morocco">Morocco</option>
                    <option value="Mozambique">Mozambique</option>
                    <option value="Myanmar, {Burma}">Myanmar, {Burma}</option>
                    <option value="Namibia">Namibia</option>
                    <option value="Nauru">Nauru</option>
                    <option value="Nepal">Nepal</option>
                    <option value="Netherlands">Netherlands</option>
                    <option value="New Zealand">New Zealand</option>
                    <option value="Nicaragua">Nicaragua</option>
                    <option value="Niger">Niger</option>
                    <option value="Nigeria">Nigeria</option>
                    <option value="Norway">Norway</option>
                    <option value="Oman">Oman</option>
                    <option value="Pakistan">Pakistan</option>
                    <option value="Palau">Palau</option>
                    <option value="Panama">Panama</option>
                    <option value="Papua New Guinea">Papua New Guinea</option>
                    <option value="Paraguay">Paraguay</option>
                    <option value="Peru">Peru</option>
                    <option value="Philippines">Philippines</option>
                    <option value="Poland">Poland</option>
                    <option value="Portugal">Portugal</option>
                    <option value="Qatar">Qatar</option>
                    <option value="Romania">Romania</option>
                    <option value="Russian Federation">Russian Federation</option>
                    <option value="Rwanda">Rwanda</option>
                    <option value="St Kitts & Nevis">St Kitts & Nevis</option>
                    <option value="St Lucia">St Lucia</option>
                    <option value="Saint Vincent & the Grenadines">Saint Vincent & the Grenadines</option>
                    <option value="Samoa">Samoa</option>
                    <option value="San Marino">San Marino</option>
                    <option value="Sao Tome & Principe">Sao Tome & Principe</option>
                    <option value="Saudi Arabia">Saudi Arabia</option>
                    <option value="Senegal">Senegal</option>
                    <option value="Serbia">Serbia</option>
                    <option value="Seychelles">Seychelles</option>
                    <option value="Sierra Leone">Sierra Leone</option>
                    <option value="Singapore">Singapore</option>
                    <option value="Slovakia">Slovakia</option>
                    <option value="Slovenia">Slovenia</option>
                    <option value="Solomon Islands">Solomon Islands</option>
                    <option value="Somalia">Somalia</option>
                    <option value="South Africa">South Africa</option>
                    <option value="South Sudan">South Sudan</option>
                    <option value="Spain">Spain</option>
                    <option value="Sri Lanka">Sri Lanka</option>
                    <option value="Sudan">Sudan</option>
                    <option value="Suriname">Suriname</option>
                    <option value="Swaziland">Swaziland</option>
                    <option value="Sweden">Sweden</option>
                    <option value="Switzerland">Switzerland</option>
                    <option value="Syria">Syria</option>
                    <option value="Taiwan">Taiwan</option>
                    <option value="Tajikistan">Tajikistan</option>
                    <option value="Tanzania">Tanzania</option>
                    <option value="Thailand">Thailand</option>
                    <option value="Togo">Togo</option>
                    <option value="Tonga">Tonga</option>
                    <option value="Trinidad & Tobago">Trinidad & Tobago</option>
                    <option value="Tunisia">Tunisia</option>
                    <option value="Turkey">Turkey</option>
                    <option value="Turkmenistan">Turkmenistan</option>
                    <option value="Tuvalu">Tuvalu</option>
                    <option value="Uganda">Uganda</option>
                    <option value="Ukraine">Ukraine</option>
                    <option value="United Arab Emirates">United Arab Emirates</option>
                    <option value="United Kingdom">United Kingdom</option>
                    <option value="United States">United States</option>
                    <option value="Uruguay">Uruguay</option>
                    <option value="Uzbekistan">Uzbekistan</option>
                    <option value="Vanuatu">Vanuatu</option>
                    <option value="Vatican City">Vatican City</option>
                    <option value="Venezuela">Venezuela</option>
                    <option value="Vietnam">Vietnam</option>
                    <option value="Yemen">Yemen</option>
                    <option value="Zambia">Zambia</option>
                    <option value="Zimbabwe">Zimbabwe</option>
                </select>
            </label>
            <label>
                <input type="text" class="form-control" placeholder="Postal code" name="postal_code" required>
            </label>
            <label>
                <select class="form-control" name="preferred_contact_mode" required>
                    <option value="" selected>Preferred form of contact</option>
                    <option value="Email">Email</option>
                    <option value="Phone">Phone</option>
                </select>
            </label>
            <label>
                <select class="form-control" name="preferred_payment_option" required>
                    <option value="" selected>Preferred form of payment</option>
                    <option value="USD">USD</option>
                    <option value="Euro">Euro</option>
                    <option value="Bitcoin">Bitcoin</option>
                </select>
            </label>
            <label>
                <select class="form-control" name="donation_interval" required>
                    <option value="" selected>Frequency of donation</option>
                    <option value="Yearly">Yearly</option>
                    <option value="Monthly">Monthly</option>
                    <option value="One-time">One-time</option>
                </select>
            </label>
            <label>
                <input type="number" class="form-control" placeholder="Amount of donation" name="amount" required>
            </label>
            <label>
                <textarea name="comments" class="text-area" cols="30" rows="10" placeholder="Drop a comment" required></textarea>
            </label>
            <button class="button">REVIEW</button>
        </form>

        <div js-review-block style="margin-bottom: 40px; display: none">
            <h3>REVIEW</h3>
            <div js-review>
            </div>
            <div style="display: flex;">
                <button js-submit-btn class="button">CONFIRM</button>
                <a href="<?= \App\Classes\Helper::url('cancel') ?>" class="button accent">CANCEL</a>
            </div>
        </div>

        <div id="infobox-wrapper">
            <h3>Where your donation goes</h3>
            <p><b>Technology</b>: Servers, bandwidth, maintenance, development. Wikipedia is one of the top 10 websites
                in the world, and it runs on a fraction of what other top websites spend.
            </p>
            <p><b>People and Projects</b>: The other top websites have thousands of employees. We have about 400 staff
                and contractors to support a wide variety of projects, making your donation a great investment in a
                highly-efficient not-for-profit organization.
            </p>
        </div>
    </div>
</main>

<script>
    const currencies = {
        usd: {rate: 1, symbol: '&#36;'},
        euro: {rate: 1.19, symbol: '&#128;'},
        bitcoin: {rate: 40038.80, symbol: '&#8383;'},
    }
    const numberFormat = (new Intl.NumberFormat).format;

    function getAnnualDonation({amount, preferred_currency, interval}) {
        const currency = currencies[preferred_currency.toLowerCase()]
        let usd = '';


        if (interval === 'Monthly') {
            if (preferred_currency !== 'USD') {
                usd = ` (${currencies.usd.symbol}${numberFormat(amount * currency.rate * 12)})`;
            }

            return `${currency.symbol}${numberFormat(amount * 12)}${usd}`
        }
        if (preferred_currency !== 'USD') {
            usd = ` (${currencies.usd.symbol}${numberFormat(amount * currency.rate)})`;
        }

        return `${currency.symbol}${numberFormat(amount)}${usd}`
    }

    function showReview(event) {
        event.preventDefault();

        const data = new FormData(event.target);
        const values = Object.fromEntries(data.entries());

        const address = [
            values.street_address, values.city+ ' '+ values.postal_code, values.state, values.country
        ].filter(item => item).join(', ');
        const annualMoney = getAnnualDonation({
            amount: values.amount,
            preferred_currency: values.preferred_payment_option,
            interval: values.donation_interval,
        })

        document.querySelector('div[js-review]').innerHTML = `
                <p style="margin-bottom: 5px; text-transform: capitalize;"><b>${values.first_name} ${values.last_name}</b></p>
                <a href="tel:${values.phone}">${values.phone}</a>
                <a style="margin-left: 5px; display: block" href="mailto:${values.email}">${values.email}</a>
                <p><b>Address</b>: <span style="text-transform: capitalize">${address}</span></p>
                <p><b>Preferred mode of contact</b>: ${values.preferred_contact_mode}</p>
                <p><b>Preferred payment</b>: ${values.preferred_payment_option}</p>
                <p><b>Donation in a year</b>: ${annualMoney}</p>
                ${values.comments ? `<p><b>Comments</b><br>${values.comments}</p>` : ''}
        `;
        document.querySelector('form[js-form]').style.display = 'none';
        document.querySelector('div[js-review-block]').style.display = 'block';
    }

    function submit(event) {
        event.preventDefault();

        const body = new FormData(document.querySelector('form[js-form]'));

        fetch('donation/store', {
            headers: {'Content-Type': 'application/json'},
            mode: 'no-cors',
            method: 'post',
            body
        }).then(async response => {
            if (response.ok) {
                window.location.replace('confirmed');
                return;
            }

            if (response.status === 422) {
                const error = await response.json()
                alert(error);
            }

            alert('something went wrong on the server')
        })
    }

    (function () {
        const form = document.querySelector('form[js-form]');
        form.addEventListener('submit', showReview);

        document.querySelector('button[js-submit-btn]').addEventListener('click', submit);
    })();

</script>
</body>
</html>
